//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsXtraSchedulingEntities1 : DbContext
    {
        public CarsXtraSchedulingEntities1()
            : base("name=CarsXtraSchedulingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            
            base.OnModelCreating(modelBuilder);
        }
    
        public DbSet<Car> Cars { get; set; }
        public DbSet<CarScheduling> CarSchedulings { get; set; }
    }
}
