'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace SchedulerEntityFramework

    Public Partial Class Car

        Public Property ID As Integer

        Public Property Trademark As String

        Public Property Model As String

        Public Property HP As Short?

        Public Property Liter As Double?

        Public Property Cyl As Short?

        Public Property TransmissSpeedCount As Short?

        Public Property TransmissAutomatic As String

        Public Property MPG_City As Short?

        Public Property MPG_Highway As Short?

        Public Property Category As String

        Public Property Description As String

        Public Property Hyperlink As String

        Public Property Picture As Byte()

        Public Property Price As Decimal?

        Public Property RtfContent As String
    End Class
End Namespace
