Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace SchedulerEntityFramework

    Partial Public Class CarScheduling
        Public Property ID() As Integer
        Public Property CarId() As String
        Public Property UserId() As Integer?
        Public Property Status() As Integer?
        Public Property Subject() As String
        Public Property Description() As String
        Public Property Label() As Integer?
        Public Property StartTime() As Date?
        Public Property EndTime() As Date?
        Public Property Location() As String
        Public Property AllDay() As Boolean
        Public Property EventType() As Integer?
        Public Property RecurrenceInfo() As String
        Public Property ReminderInfo() As String
        Public Property Price() As Decimal?
        Public Property ContactInfo() As String
        Public Property Usercode() As String
        Public Property OriginalStartTime() As Date?
        Public Property OriginalEndTime() As Date?
    End Class
End Namespace
