'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace SchedulerEntityFramework

    Public Partial Class CarsXtraSchedulingEntities1
        Inherits DbContext

        Public Sub New()
            MyBase.New("name=CarsXtraSchedulingEntities1")
        End Sub

        Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub

        Public Property Cars As DbSet(Of Car)

        Public Property CarSchedulings As DbSet(Of CarScheduling)
    End Class
End Namespace
